site:
  theme: 'StriktTheme'
  baseUrl: 'https://strikt.io/'
  about:
    siteName: Strikt
    siteDescription: Strikt is an assertion library for Kotlin intended for use with a test runner such as JUnit or Spek.

theme:
  social:
    other:
    - label: 'GitHub'
      icon: 'fa-github'
      link: 'https://github.com/robfletcher/strikt/'
      buttonColor: 'dark'
    - label: 'Slack'
      icon: 'fa-slack-hash'
      link: 'https://kotlinlang.slack.com/messages/CAR7KJ96J'
      buttonColor: 'danger'
    - label: 'Twitter'
      icon: 'fa-twitter'
      link: 'https://twitter.com/stri_kt'
      buttonColor: 'info'
  menu:
  - type: 'page'
    title: 'Home'
    itemId: 'home'
    icon: 'home'
  - type: 'wiki'
    icon: 'graduation-cap'
    asSubmenu: true
    submenuTitle: 'User Guide'
  - type: 'submenu'
    title: 'API'
    icon: 'book'
    menu:
    - type: 'sourcedocModules'
      moduleType:  'kotlindoc'
      moduleGroup: 'core'
    - type: 'sourcedocModules'
      moduleType:  'kotlindoc'
      moduleGroup: 'bom'
    - type: 'separator'
    - type: 'sourcedocModules'
      moduleType:  'kotlindoc'
      moduleGroup: 'module'
  - type: 'submenu'
    title: 'Information'
    icon: 'info-circle'
    menu:
    - type: 'page'
      title: 'About Strikt'
      itemId: 'About Strikt'
    - type: 'page'
      itemId: 'Changelog'
  metaComponents:
    - type: 'orchidSearch'
      extraCss: ['assets/css/orchidSearch.scss']
    - type: 'prism'
      extraCss: ['assets/css/prismFixes.scss']
      theme: 'tomorrow'
      languages:
        - 'clike'
        - 'kotlin'

services:
  publications:
    stages:
    - type: githubPages
      branch: gh-pages
      username: robfletcher
      repo: strikt

kotlindoc:
  # Uncomment `homePageOnly` line to temporarily disable Kotlin docs generation and only
  #   generate module homepages. Dokka takes a few seconds to start up, which
  #   makes rapid iteration a bit painful, so it may be helpful to disable it
  #   when making changes to the site.
#  homePageOnly: true
  homePagePermalink:   'modules/:module'
  sourcePagePermalink: ':moduleType/:module/:sourceDocPath'
  modules:
    - { name: 'Core API',          slug: 'core',     sourceDirs: '../../../../strikt-core/src/main/kotlin/',      moduleGroup: 'core'   }
    - { name: 'Bill of Materials', slug: 'bom',      sourceDirs: '../../../../strikt-bom/src/main/kotlin/',       moduleGroup: 'bom'    }
    - { name: 'Arrow Module',      slug: 'arrow',    sourceDirs: '../../../../strikt-arrow/src/main/kotlin/',     moduleGroup: 'module' }
    - { name: 'Gradle Module',     slug: 'gradle',   sourceDirs: '../../../../strikt-gradle/src/main/kotlin/',    moduleGroup: 'module' }
    - { name: 'Jackson Module',    slug: 'jackson',  sourceDirs: '../../../../strikt-jackson/src/main/kotlin/',   moduleGroup: 'module' }
    - { name: 'Java Module',       slug: 'java',     sourceDirs: '../../../../strikt-java-time/src/main/kotlin/', moduleGroup: 'module' }
    - { name: 'MockK Module',      slug: 'mockk',    sourceDirs: '../../../../strikt-mockk/src/main/kotlin/',     moduleGroup: 'module' }
    - { name: 'Protobuf Module',   slug: 'protobuf', sourceDirs: '../../../../strikt-protobuf/src/main/kotlin/',  moduleGroup: 'module' }
    - { name: 'Spring Module',     slug: 'spring',   sourceDirs: '../../../../strikt-spring/src/main/kotlin/',    moduleGroup: 'module' }

snippets:
  sections:
    - tags: ['code_snippets']
      adapter:
        type: 'embedded'
        baseDirs:
            - '../../../../strikt-core/src/test/kotlin/'
            - '../../../../strikt-bom/src/test/kotlin/'
            - '../../../../strikt-arrow/src/test/kotlin/'
            - '../../../../strikt-gradle/src/test/kotlin/'
            - '../../../../strikt-jackson/src/test/kotlin/'
            - '../../../../strikt-java-time/test/main/kotlin/'
            - '../../../../strikt-mockk/src/test/kotlin/'
            - '../../../../strikt-protobuf/src/test/kotlin/'
            - '../../../../strikt-spring/src/test/kotlin/'
        recursive: true
        startPattern: '^.*?//.*?START(.+?)$'
        endPattern: '^.*?//.*?END(.+?)$'
        patternNameGroup: 1
